public class exception2 {
    public static void main(String[] args) {
       int[] arr={1,2,3,45};
       try{
        System.out.println(arr[5]);
       } 
       catch(Exception e){
        System.out.println(e);
       }
       System.out.println("jai hind");
    }
    
}
